repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
-   repo: local
    hooks:
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]
        args: ['--line-length=120']
    -   id: ruff
        name: ruff
        description: 'An extremely fast Python linter, written in Rust.'
        entry: ruff
        language: python
        types: [python]
        args: ['--line-length=120', "--force-exclude", "--select=E,F,N,W,UP,Q"]